### ISSUE TITLE
error.reason is undefined when running tests with RevertTraceSubprovider

### ISSUE THREAD

**Issue by WyseNynja** [0xProject/dev-tools-truffle-example#10]
I have a test that looks something like this:
```
    try {
      await contractInstance.foobar(1);

      assert.fail("the above await was supposed to revert");
    } catch (error) {
      // if error.reason is undefined, this failed for some unexpected reason
      if (error.reason === undefined) {
        console.log("error.reason is undefined");
        console.log(error);
      }

      assert.equal(error.reason, "UNABLE_REPAY_ETH");
    }
```

When I run `truffle test`, everything passes

When I run `MODE=trace truffle test`, this test fails. Is this an intentional side-effect of RevertTraceSubprovider? How should I be checking the revert reason? The logs have helpful output, but I want to access that log from my test.

```

Stack trace for REVERT:

/usr/src/app/contracts-sol-compiler/Foobar.sol:176:8:
        require(address(this).balance >= borrow_wei, "UNABLE_REPAY_ETH")




Stack trace for REVERT:

/usr/src/app/contracts-sol-compiler/Foobar.sol:176:8:
        require(address(this).balance >= borrow_wei, "UNABLE_REPAY_ETH")


error.reason is undefined
Error: VM Exception while processing transaction: revert UNABLE_REPAY_ETH
    at WebsocketSubprovider._handleSocketMessage (/usr/src/app/node_modules/web3-provider-engine/subproviders/websocket.js:121:18)
    at WebSocket.onMessage (/usr/src/app/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/usr/src/app/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/usr/src/app/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/usr/src/app/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/usr/src/app/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/usr/src/app/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at Socket.socketOnData (/usr/src/app/node_modules/ws/lib/websocket.js:795:35)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
    1) ... should revert if trade isn't an arbitrage
    > No events were emitted
```

For now I'm going to wrap this check in a `if (global.mode != "trace") { ... }`. I could also parse the error text myself, but this feels like a bug.

**Comment by WyseNynja** [comment]
Let me know if I should open this as an issue on the repo with RevertTraceSubprovider instead. This does seem like it would belong better over there.

**Comment by LogvinovLeon** [comment]
Yes. Please open it there. Definitely a bug

**Comment by WyseNynja** [comment]
Closing in favor of https://github.com/0xProject/0x-monorepo/issues/1664
