### ISSUE TITLE
Error: Cannot find module './common'

### ISSUE THREAD

**Issue by isaacsultan** [0xProject/dev-tools-truffle-example#6]
# Usage

```
npm i
docker run -it --rm -p 8545:8501 0xorg/devnet
yarn trace
```

# Stacktrace

```
yarn run v1.12.3
$ MODE=trace truffle test
Compiling ./contracts/MetaCoin.sol...
Compiling ./contracts/Migrations.sol...
Compiling ./contracts/SafeMath.sol...
Error: Cannot find module './common'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Suite.<anonymous> (/Users/isaacsultan/Code/dev-tools-truffle-example/node_modules/mocha/lib/interfaces/bdd.js:30:18)
    at emitThree (events.js:141:20)
    at Suite.emit (events.js:217:7)
    at /Users/isaacsultan/Code/dev-tools-truffle-example/node_modules/mocha/lib/mocha.js:230:11
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/isaacsultan/Code/dev-tools-truffle-example/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/isaacsultan/Code/dev-tools-truffle-example/node_modules/mocha/lib/mocha.js:536:10)
    at /Users/isaacsultan/Code/dev-tools-truffle-example/node_modules/truffle/build/cli.bundled.js:582817:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Truffle v5.0.2 (core: 5.0.2)
Node v8.9.3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by LogvinovLeon** [comment]
Hi @isaacsultan . Unfortunately, I wasn't able to reproduce it. I've used your exact version of node.

**Comment by LogvinovLeon** [comment]
Also - after https://github.com/trufflesuite/ganache-core/issues/280 got fixed you're able to use sol-trace with Ganache instead of Geth. Could you please try that? I've updated the example repo.

**Comment by isaacsultan** [comment]
@LogvinovLeon Great, all working now with new version and Ganache!
